blank_issues_enabled: true
contact_links:
  - name: Book
    url: https://mlr3book.mlr-org.com/
    about: Book about the mlr3 ecosystem

  - name: Website
    url: https://mlr-org.com
    about: The central website of mlr-org

  - name: Stack Overflow
    url: https://stackoverflow.com/questions/tagged/mlr3
    about: Questions about mlr3 on Stack Overflow
